# ===================================================================
# CONFIGURACIÓN ESENCIAL PARA TU SITIO CON HYDEJACK (CORREGIDA)
# ===================================================================

# --- Información Básica del Sitio ---
# REEMPLAZA 'tu-usuario' con tu nombre de usuario de GitHub
url:              https://tu-usuario.github.io
baseurl:          "" # Déjalo vacío
lang:             es-ES # Idioma del sitio
title:            Cristian Cartagena Matos # Título en la pestaña del navegador
description: >-   # Descripción para Google
  Portafolio de Cristian Cartagena Matos, Ingeniero de Minas especialista
  en Planeamiento, Despacho y Ciencia de Datos.

# --- Información del Autor (para la barra lateral) ---
author:
  name:           Cristian Cartagena Matos
  email:          ccartagenamatos@gmail.com

# --- Menú de Navegación (en la barra lateral) ---
menu:
  - title:          Sobre mí
    url:            /

  - title:          Experiencia
    url:            /experiencia/

  - title:          Habilidades y Educación
    url:            /habilidades/

  - title:          Blog
    url:            /blog/ # Para futuros artículos

# --- Estilo y Tema ---
# theme: jekyll-theme-hydejack # Comentado para evitar el error
remote_theme: hydecorp/hydejack@v9 # Usamos remote_theme para que funcione en GitHub Pages

hydejack:
  no_break_layout:  true # Mantiene el contenido centrado
copyright:          "© 2024 Cristian Cartagena Matos. Todos los derechos reservados."

# --- Plugins y Exclusiones (déjalo como está) ---
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links

exclude:
  - .jekyll-cache
  - .sass-cache
  - vendor
  - Gemfile
  - Gemfile.lock
